 var loc= {
'vmp':'Middle point voltage V<sub>mp</sub>',
'vor':'V or ',
'not_connected':'NOT CONNECTED',
'V':'V',
'W':'W',
'U':'V',
'title1':'Vin',
'title2':'Iin,A',
'title3':'Vout',
'title4':'Itotal,A',
'title5':'Vbat',
'title6':'Ibat-mac,A',
'title7':'Ibat,A',
'title8':'V',
'alert1':'Counter reset',
'off1':'OFF',
'hz':'Hz',
'map_mode':'MAC mode',
'undefined':'UNDEFINED',
'kwh_day':'kWh/day',
'min':'min',
'ah':'Ah',
'h':'h',
'na':'n/a',
'temp':'temperature',
'text1':'Battery voltage, V',
'loading':'Data loading...',
'text2':'Vbat, %pavgV',
'text3':'Voltage, V',
'text4':'Vin, %pavgV',
'text5':'Vout, %pavgV',
'text6':'Power, W',
'text7':'Pin, %pavgVA',
'text8':'Pbat-mac, %pavgW',
'text9':'Pmppt_out, %pavgW',
'text10':'Current, A',
'text11':'Iin, %pavgA',
'text12':'Ibat-mac, %pavgA',
'text13':'Imppt-bat, %pavgA',
'text14':'MPPT curent (from MPPT), A',
'text15':'CS1, %pavgA',
'text16':'CS2, %pavgA',
'text17':'Battery powers balance, W. Data source - MAC (I2C)',
'text18':'Pbal, %pavgW',
'text19':'Battery currents balance, A. Data source- MAC (I2C)',
'text20':'Itotal, %pavgA',
'text21':'Wind generator rpm',
'text22':'n, %pavg rpm',
'text23':'Battery currents balance, A. Data source - MPPT (Hall sensors)',
'text24':'Battery powers balance,W. Data source - MPPT (Hall sensors)',
'working':'Running',
'not_working':'Stopped',
'alert1':'Data read error',
'text25':'select from the list',
'sec':'s',
'minval':'Minimal value: ',
'maxval':'Maximal value: ',
'note1':'Time is set in 24h format with 10min step, for example 23:50',
'note2':'Time is set in hours',
'finished':'Process is over',
'text26':'Battery 1',
'text27':'Garage',
'MAC':'MAC',
'MPPT':'MPPT',
'text28':'Noting selected',
'text29':'Data saved',
'text30':'Saved',
'text31':'Are you sure? All the nodes will be deleted from the database!',
'text32':'The nodes are deleted',
};

var map_mode=["MAC is ON. No grid at the input.","MAC is OFF. Grid is detected ","MAC is ON. AB generation. No grid.","MAC is on. Grid transmitting","MAC is ON. Transmitting+Charge","","","","","",
    "Forced generation","Tariff zone. Maximal rate. Forced generation", "Tariff zone. Minimal rate.",
    "Transmitting + ECO mixing", "Transmitting + surplus to the grid", "Waiting for external full charge", "Tariff zone. Transmitting + ECO-mixing",
    "Tariff zone. Transmiting + Surplus to the grid", "Pmax mixing"];
    charge_mode=["","","1st stage","Float","","","2nd stage","","","","Absorption","","","","Absorption"],
    error_status=[
    "Critical error!",
    "Battery is discharged. The voltage is too low for MAC operation.",
    "Battery overvoltage! Generation or charge is suspended.",
    "Short Sircuit current on AB while charging. Generation or charge is suspended.",
    "Short Sircuit current on AB. Charge is suspended.",
    "Main relay sticking, maintenance is required",
    "SC current on AC, MAC will activate generation mode. MAC will be turned off in case of SC on AB.",
    "Extraneous voltage at the output. MAC stops the generation!",
    "Reset occured",
    "Battery is fully discharged. MAC will work for 1 minute.",
    "Battery overload, MAC stops the generation in 10sec",
    "The load is above the nominal rate. MAC will work for limited time.",
    "Overheat, generation will be suspended.",
    "Fan error",
    "AC overload. Switch to generation mode.",
    "Operation mode failure (surge)",
    "Shutdown on multiple short sircuits at charge. Error will be reset in 2 hr.",
    "",
    "Grid voltage is out of range",
    "Extraneous voltage at the output, or heavy surges caused by the load",
    "Surges on the power grid",
    "STOP or CHARGE button was sticked",
    "Switch on charge mode is impossible - no grid",
    "Load power is above maximal one",
    "Grid is unstable",
    "AB overload. MAC was stopped. 10 restart attepmts.",
    "AB overload in charge mode. MAC was stopped. 10 restart attepmts.",
    "AB critical voltage. Stopped on overload.",
    "Fan failure. 10 restart attempts.",
    "Power has been above the nominal one for 30 minutes.",
    "Full discharge AB. Stopped.",
    "Stopped. Temperature is out of range",
    "Shutdown. May AB overloads have occured",
    "Generation is stopped. Extraneous voltage at the output or relay failure.",
    "Switch to generation. AC overload",
    "","","","","","Shutdown on multiple AC overloads.",
    "MPPT: PVP overvoltage",
    "MPPT: AB overvoltage",
    "MPPT: AB overcharge",
    "MPPT: SC on AB",
    "MPPT: AB overheat",
    "MPPT: I2C error",""
    ];
var dev=['MAC','MPPT','MAC+MPPT'];